name: Windup Operator E2E Tests

on: [ pull_request,push ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # check versions in https://github.com/kubernetes/kubernetes/releases
        kubernetes_version: [ v1.24.4 ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Minikube-Kubernetes
        # check version in https://github.com/manusa/actions-setup-minikube/releases
        uses: manusa/actions-setup-minikube@v2.7.2
        with:
          # check version in https://github.com/kubernetes/minikube/releases
          minikube version: v1.28.0
          kubernetes version: ${{ matrix.kubernetes_version }}
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure Minikube
        run: |
          # Minikube addons
          minikube addons enable ingress
      - name: Test
        run: |
          mvn clean verify
